apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jx-setup
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "jx"
    tekton.dev/displayName: "jx-setup"
spec:
  description: >-
    Configure git environment. Perform it merge of latest changes if IS_RELEASE is
    true: generate new version generate as result next docker image name extract source
    branch name based on PR number
  workspaces:
    - name: source
      description: sources dir
  params:
    - description: git url to clone
      name: REPO_URL
      type: string
    - default: master
      description: git revision to checkout (branch, tag, sha, refâ€¦)
      name: PULL_PULL_SHA
      type: string
    - description: the unique build number
      name: BUILD_ID
      type: string
    - description: the name of the job which is the trigger context name
      name: JOB_NAME
      type: string
    - description: the specification of the job
      name: JOB_SPEC
      type: string
    - description: 'the kind of job: postsubmit or presubmit'
      name: JOB_TYPE
      type: string
    - default: master
      description: the base git reference of the pull request
      name: PULL_BASE_REF
      type: string
    - description: the git sha of the base of the pull request
      name: PULL_BASE_SHA
      type: string
    - default: ""
      description: git pull request number
      name: PULL_NUMBER
      type: string
    - default: ""
      description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
      name: PULL_PULL_REF
      type: string
    - description: git pull reference strings of base and latest in the form 'master:$PULL_BASE_SHA,$PULL_NUMBER:$PULL_PULL_SHA:refs/pull/$PULL_NUMBER/head'
      name: PULL_REFS
      type: string
    - description: git repository name
      name: REPO_NAME
      type: string
    - description: git repository owner (user or organisation)
      name: REPO_OWNER
      type: string
    - name: IS_RELEASE
      type: string
      default: "false"
    - name: NEXT_VERSION_ARGS
      type: string
      default: "--semantic-release --use-git-tag-only"
    - name: GIT_CHECKOUT_STRATEGY
      type: string
      default: "jx"
  results:
    - name: image
      description: Name of the image which should be builded
    - name: source_branch
      description: name of the source branch
  stepTemplate:
    env:
      - name: BUILD_ID
        value: $(params.BUILD_ID)
      - name: JOB_NAME
        value: $(params.JOB_NAME)
      - name: JOB_SPEC
        value: $(params.JOB_SPEC)
      - name: JOB_TYPE
        value: $(params.JOB_TYPE)
      - name: PULL_BASE_REF
        value: $(params.PULL_BASE_REF)
      - name: PULL_BASE_SHA
        value: $(params.PULL_BASE_SHA)
      - name: PULL_NUMBER
        value: $(params.PULL_NUMBER)
      - name: PULL_PULL_REF
        value: $(params.PULL_PULL_REF)
      - name: PULL_PULL_SHA
        value: $(params.PULL_PULL_SHA)
      - name: PULL_REFS
        value: $(params.PULL_REFS)
      - name: REPO_NAME
        value: $(params.REPO_NAME)
      - name: REPO_OWNER
        value: $(params.REPO_OWNER)
      - name: REPO_URL
        value: $(params.REPO_URL)
  steps:
    - name: git-configure
      image: gcr.io/jenkinsxio/jx-boot:3.1.43
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh

        echo "Dir: $(pwd)"

        git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
        git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
        git config --global credential.helper store

        git fetch

        git checkout $(params.PULL_PULL_SHA)
        echo checked out revision: $(params.PULL_PULL_SHA) to dir: $(workspaces.source.path)
    - name: git-setup
      image: gcr.io/jenkinsxio/jx-boot:3.1.43
      workingDir: $(workspaces.source.path)
      script: |
        jx gitops git setup --namespace jx-git-operator
    - name: get-pr-info
      image: gcr.io/jenkinsxio/jx-boot:3.1.43
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        if [[ -n "${PULL_NUMBER}" ]]; then
          jx gitops pr get --git-token="$GIT_TOKEN" --pr="${PULL_NUMBER}" &> pr.yaml
        fi
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: jx-pipeline-git-github-github
              key: password
    - name: save-source-branch
      workingDir: $(workspaces.source.path)
      image: mikefarah/yq:3.3.4
      script: |
        if [[ -n "${PULL_NUMBER}" ]]; then
          yq r pr.yaml Source > $(results.source_branch.path)
          rm pr.yaml
          echo "Soure branch is: $(cat $(results.source_branch.path))"
        fi
    - name: git-merge
      image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
      workingDir: $(workspaces.source.path)
      script: |
        if [[ "$(params.GIT_CHECKOUT_STRATEGY)" == "jx" ]]; then
          jx step git merge --verbose --baseSHA $(params.PULL_BASE_SHA) --sha $(params.PULL_PULL_SHA) --baseBranch $(params.PULL_BASE_REF)
        else
          git checkout $(cat $(results.source_branch.path))
        fi
    - name: next-version
      image: gcr.io/jenkinsxio/builder-go
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        if $(params.IS_RELEASE); then
            if jx step next-version $(params.NEXT_VERSION_ARGS); then
              echo "New version: $(cat VERSION)"
            else
              echo "Original next-version command faled using simple one."
              jx step next-version --use-git-tag-only
            fi
          else
            echo "Skipping version update [file]"
        fi
    - name: jx-variables
      image: gcr.io/jenkinsxio/jx-boot:3.1.43
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        jx gitops variables
    - name: jx-variables-results
      image: gcr.io/jenkinsxio/jx-cli:3.1.43
      script: |
        #!/usr/bin/env bash
        source $(workspaces.source.path)/.jx/variables.sh
        export OUTPUT_IMAGE=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        echo -n "$OUTPUT_IMAGE" > $(results.image.path)
