apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: secrets-scanner
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: security
    tekton.dev/displayName: "git leaks scanner"
spec:
  description: >-
    run gitleaks scan.
    see https://github.com/zricethezav/gitleaks
  workspaces:
    - name: source
  params:
    - name: PR_ID
      description: PULL Request ID
    - name: CONFIG_FILE
      description: "path to gitleaks config file"
      default: ".lighthouse/secrets/gitleaks.toml"
    - name: PULL_BASE_SHA
      description: PULL_BASE_SHA
    - name: LAST_SHA
      description: last SHA
    - name: REPORT_PATH
      description: where report should be stored
      default: ".report.json"
  results:
    - name: status
      description: scan status
  steps:
    - name: scan-secrets
      image: zricethezav/gitleaks:v7.1.0
      imagePullPolicy: IfNotPresent
      workingDir: $(workspaces.source.path)
      script: |
        git fetch
        git log --left-right --cherry-pick --pretty=format:"%H" $(params.PULL_BASE_SHA)...$(params.LAST_SHA) > commit_list.txt

        if gitleaks --path="$(workspaces.source.path)" --redact --commits-file=commit_list.txt --config-path="$(params.CONFIG_FILE)" --report="$(params.REPORT_PATH)" ; then
            echo "no leaks found"
            echo "success" > $(results.status.path)
          else
            echo "failed" > $(results.status.path)
        fi

    - name: print-report
      image: zricethezav/gitleaks:v7.1.0
      imagePullPolicy: IfNotPresent
      workingDir: $(workspaces.source.path)
      script: |
        if [[ "$(cat $(results.status.path))" == "failed" ]]; then
          cat $(params.REPORT_PATH)
        fi

    - name: comment
      image: gcr.io/jenkinsxio/jx-cli:3.1.43
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash

        if [[ "$(cat $(results.status.path))" == "failed" ]]; then
          if [[ -n "$(params.PR_ID)" ]]; then
            REPORT="$(cat $(params.REPORT_PATH))"
            echo -e ":spider: Some leaks have been found \n <details> \n\n \`\`\` \n $REPORT \n \`\`\` \n\n</details>" > .report
            jx gitops pr comment --comment="$(cat .report)" --pr="$(params.PR_ID)"
          fi
          exit 1
        fi
